// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaravmckfiviprrlibtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhcmF2bWNrZml2aXBycmxpYnRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTUxOTgsImV4cCI6MjA2NjE5MTE5OH0.7R0qWuS9AmFQQJ6x4N5mIXIbt2Qbg84AKURqIxDXlWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);